/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.wordpress.metaphorm.authProxy.sb.service.base;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.BaseLocalServiceImpl;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import com.wordpress.metaphorm.authProxy.sb.model.OAuthProvider;
import com.wordpress.metaphorm.authProxy.sb.service.OAuthConnectionLocalService;
import com.wordpress.metaphorm.authProxy.sb.service.OAuthProviderLocalService;
import com.wordpress.metaphorm.authProxy.sb.service.persistence.OAuthConnectionPersistence;
import com.wordpress.metaphorm.authProxy.sb.service.persistence.OAuthProviderPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * The base implementation of the o auth provider local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.wordpress.metaphorm.authProxy.sb.service.impl.OAuthProviderLocalServiceImpl}.
 * </p>
 *
 * @author stiansigvartsen
 * @see com.wordpress.metaphorm.authProxy.sb.service.impl.OAuthProviderLocalServiceImpl
 * @see com.wordpress.metaphorm.authProxy.sb.service.OAuthProviderLocalServiceUtil
 * @generated
 */
public abstract class OAuthProviderLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements OAuthProviderLocalService,
		IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.wordpress.metaphorm.authProxy.sb.service.OAuthProviderLocalServiceUtil} to access the o auth provider local service.
	 */

	/**
	 * Adds the o auth provider to the database. Also notifies the appropriate model listeners.
	 *
	 * @param oAuthProvider the o auth provider
	 * @return the o auth provider that was added
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public OAuthProvider addOAuthProvider(OAuthProvider oAuthProvider)
		throws SystemException {
		oAuthProvider.setNew(true);

		return oAuthProviderPersistence.update(oAuthProvider, false);
	}

	/**
	 * Creates a new o auth provider with the primary key. Does not add the o auth provider to the database.
	 *
	 * @param providerId the primary key for the new o auth provider
	 * @return the new o auth provider
	 */
	public OAuthProvider createOAuthProvider(long providerId) {
		return oAuthProviderPersistence.create(providerId);
	}

	/**
	 * Deletes the o auth provider with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param providerId the primary key of the o auth provider
	 * @return the o auth provider that was removed
	 * @throws PortalException if a o auth provider with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	public OAuthProvider deleteOAuthProvider(long providerId)
		throws PortalException, SystemException {
		return oAuthProviderPersistence.remove(providerId);
	}

	/**
	 * Deletes the o auth provider from the database. Also notifies the appropriate model listeners.
	 *
	 * @param oAuthProvider the o auth provider
	 * @return the o auth provider that was removed
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	public OAuthProvider deleteOAuthProvider(OAuthProvider oAuthProvider)
		throws SystemException {
		return oAuthProviderPersistence.remove(oAuthProvider);
	}

	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(OAuthProvider.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return oAuthProviderPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return oAuthProviderPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return oAuthProviderPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return oAuthProviderPersistence.countWithDynamicQuery(dynamicQuery);
	}

	public OAuthProvider fetchOAuthProvider(long providerId)
		throws SystemException {
		return oAuthProviderPersistence.fetchByPrimaryKey(providerId);
	}

	/**
	 * Returns the o auth provider with the primary key.
	 *
	 * @param providerId the primary key of the o auth provider
	 * @return the o auth provider
	 * @throws PortalException if a o auth provider with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public OAuthProvider getOAuthProvider(long providerId)
		throws PortalException, SystemException {
		return oAuthProviderPersistence.findByPrimaryKey(providerId);
	}

	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return oAuthProviderPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the o auth providers.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param start the lower bound of the range of o auth providers
	 * @param end the upper bound of the range of o auth providers (not inclusive)
	 * @return the range of o auth providers
	 * @throws SystemException if a system exception occurred
	 */
	public List<OAuthProvider> getOAuthProviders(int start, int end)
		throws SystemException {
		return oAuthProviderPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of o auth providers.
	 *
	 * @return the number of o auth providers
	 * @throws SystemException if a system exception occurred
	 */
	public int getOAuthProvidersCount() throws SystemException {
		return oAuthProviderPersistence.countAll();
	}

	/**
	 * Updates the o auth provider in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param oAuthProvider the o auth provider
	 * @return the o auth provider that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public OAuthProvider updateOAuthProvider(OAuthProvider oAuthProvider)
		throws SystemException {
		return updateOAuthProvider(oAuthProvider, true);
	}

	/**
	 * Updates the o auth provider in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param oAuthProvider the o auth provider
	 * @param merge whether to merge the o auth provider with the current session. See {@link com.liferay.portal.service.persistence.BatchSession#update(com.liferay.portal.kernel.dao.orm.Session, com.liferay.portal.model.BaseModel, boolean)} for an explanation.
	 * @return the o auth provider that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public OAuthProvider updateOAuthProvider(OAuthProvider oAuthProvider,
		boolean merge) throws SystemException {
		oAuthProvider.setNew(false);

		return oAuthProviderPersistence.update(oAuthProvider, merge);
	}

	/**
	 * Returns the o auth connection local service.
	 *
	 * @return the o auth connection local service
	 */
	public OAuthConnectionLocalService getOAuthConnectionLocalService() {
		return oAuthConnectionLocalService;
	}

	/**
	 * Sets the o auth connection local service.
	 *
	 * @param oAuthConnectionLocalService the o auth connection local service
	 */
	public void setOAuthConnectionLocalService(
		OAuthConnectionLocalService oAuthConnectionLocalService) {
		this.oAuthConnectionLocalService = oAuthConnectionLocalService;
	}

	/**
	 * Returns the o auth connection persistence.
	 *
	 * @return the o auth connection persistence
	 */
	public OAuthConnectionPersistence getOAuthConnectionPersistence() {
		return oAuthConnectionPersistence;
	}

	/**
	 * Sets the o auth connection persistence.
	 *
	 * @param oAuthConnectionPersistence the o auth connection persistence
	 */
	public void setOAuthConnectionPersistence(
		OAuthConnectionPersistence oAuthConnectionPersistence) {
		this.oAuthConnectionPersistence = oAuthConnectionPersistence;
	}

	/**
	 * Returns the o auth provider local service.
	 *
	 * @return the o auth provider local service
	 */
	public OAuthProviderLocalService getOAuthProviderLocalService() {
		return oAuthProviderLocalService;
	}

	/**
	 * Sets the o auth provider local service.
	 *
	 * @param oAuthProviderLocalService the o auth provider local service
	 */
	public void setOAuthProviderLocalService(
		OAuthProviderLocalService oAuthProviderLocalService) {
		this.oAuthProviderLocalService = oAuthProviderLocalService;
	}

	/**
	 * Returns the o auth provider persistence.
	 *
	 * @return the o auth provider persistence
	 */
	public OAuthProviderPersistence getOAuthProviderPersistence() {
		return oAuthProviderPersistence;
	}

	/**
	 * Sets the o auth provider persistence.
	 *
	 * @param oAuthProviderPersistence the o auth provider persistence
	 */
	public void setOAuthProviderPersistence(
		OAuthProviderPersistence oAuthProviderPersistence) {
		this.oAuthProviderPersistence = oAuthProviderPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the resource remote service.
	 *
	 * @return the resource remote service
	 */
	public ResourceService getResourceService() {
		return resourceService;
	}

	/**
	 * Sets the resource remote service.
	 *
	 * @param resourceService the resource remote service
	 */
	public void setResourceService(ResourceService resourceService) {
		this.resourceService = resourceService;
	}

	/**
	 * Returns the resource persistence.
	 *
	 * @return the resource persistence
	 */
	public ResourcePersistence getResourcePersistence() {
		return resourcePersistence;
	}

	/**
	 * Sets the resource persistence.
	 *
	 * @param resourcePersistence the resource persistence
	 */
	public void setResourcePersistence(ResourcePersistence resourcePersistence) {
		this.resourcePersistence = resourcePersistence;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		PersistedModelLocalServiceRegistryUtil.register("com.wordpress.metaphorm.authProxy.sb.model.OAuthProvider",
			oAuthProviderLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"com.wordpress.metaphorm.authProxy.sb.model.OAuthProvider");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
	}

	protected Class<?> getModelClass() {
		return OAuthProvider.class;
	}

	protected String getModelClassName() {
		return OAuthProvider.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = oAuthProviderPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = OAuthConnectionLocalService.class)
	protected OAuthConnectionLocalService oAuthConnectionLocalService;
	@BeanReference(type = OAuthConnectionPersistence.class)
	protected OAuthConnectionPersistence oAuthConnectionPersistence;
	@BeanReference(type = OAuthProviderLocalService.class)
	protected OAuthProviderLocalService oAuthProviderLocalService;
	@BeanReference(type = OAuthProviderPersistence.class)
	protected OAuthProviderPersistence oAuthProviderPersistence;
	@BeanReference(type = CounterLocalService.class)
	protected CounterLocalService counterLocalService;
	@BeanReference(type = ResourceLocalService.class)
	protected ResourceLocalService resourceLocalService;
	@BeanReference(type = ResourceService.class)
	protected ResourceService resourceService;
	@BeanReference(type = ResourcePersistence.class)
	protected ResourcePersistence resourcePersistence;
	@BeanReference(type = UserLocalService.class)
	protected UserLocalService userLocalService;
	@BeanReference(type = UserService.class)
	protected UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private OAuthProviderLocalServiceClpInvoker _clpInvoker = new OAuthProviderLocalServiceClpInvoker();
}